{
 "title": "Info API",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "path", "label": "path", "query": { "query": "label_values(path)" } },
   { "name": "method", "label": "Method", "query": { "query": "label_values(method)" } },
   { "name": "status", "label": "Status", "query": { "query": "label_values(status)" } }
  ]
 },
 "panels": [
  {
   "title": "Informações da API",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p><br></p>\n<div style=\"text-align: center;\"><span style=\"color: yellow; font-size: 48px\"> Requisições Gateway</span></div>\n<p><br></p>\n"
   }
  },
  {
   "title": "Total de requisições",
   "type": "timeseries",
   "description": "Dashboard que trata o total de requisições por endpoint no intervalo definido.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_duration_seconds_count{method=\"$method\"}[$__range])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de resposta",
   "type": "timeseries",
   "description": "Dashboard que representa o tempo de resposta de cada endpoint.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"$status\"}[$__range])\r\n/\r\nrate(flask_http_request_duration_seconds_count{status=\"$status\"}[$__range])",
     "legendFormat": "{{path}} {{status}} {{method}}"
    }
   ]
  },
  {
   "title": "Latência média",
   "type": "timeseries",
   "description": "Dashboard que contempla a latência média por endpoint dividido por percentile.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(flask_http_request_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(flask_http_request_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(flask_http_request_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(flask_http_request_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(flask_http_request_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "25%"
    }
   ]
  },
  {
   "title": "Quantidade de erros servidor ",
   "type": "stat",
   "description": "Dashboard que exibe os erros do lado servidor.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_duration_seconds_count{method=\"$method\", path=\"$path\", status=~\"5..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de erros",
   "type": "timeseries",
   "description": "Dashboard que exibe a taxa de erros do lado servidor.",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{method=\"$method\", path=\"$path\", status!=\"500\"}[$__range]))\r\n/\r\nsum(rate(flask_http_request_duration_seconds_count{method=\"$method\", path=\"$path\"}[$__range]))\r\n",
     "legendFormat": "Erro 500"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quantidade de requisições",
     "type": "stat",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flask_http_request_duration_seconds_count{path=\"$path\"} ",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Quantidade de usuarios online",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 34 },
     "targets": [
      { "expr": "quantidade_usuarios_online", "legendFormat": "{{job}}" },
      { "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}