global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets: [ 'app:5000' ] #docker cria uma rede própria, referencio pelo próprio nome o compose